version: '3.8'

services:
  postgres:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=calendar
      - POSTGRES_USER=calendar
      - POSTGRES_PASSWORD=calendar
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - calendar

  calendar:
    image: calendar:develop
    build:
      dockerfile: build/calendar/Dockerfile
    environment:
      - POSTGRES_DB=calendar
      - POSTGRES_USER=calendar
      - POSTGRES_PASSWORD=calendar
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - calendar

networks:
  calendar:

volumes:
  pgdata: